# ==========================================
#        CONFIGURATION STARSHIP
# ==========================================

add_newline = false

# Le prompt actif normal ne contient QUE la flèche !
format = "$character"

# --- Modules (On les garde ici pour que Zsh puisse les récupérer) ---

[directory]
style = "bold #C29629"
format = "[  $path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "italic #5A9494"
format = "[$symbol$branch]($style) "

[character]
success_symbol = "[❯](bold #A32335) "
error_symbol = "[✗](bold #C2293F) "
