# --- Police d'ecriture ---
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

# --- Apparence de la fenetre ---
# Ajoute une petite marge intérieure pour que le texte ne colle pas aux bords
window_padding_width 10

# Rend le font légèrement transparent
# 1.0 = opaque, 0.0 = invisible
background_opacity 0.85

# --- Theme de couleurs ---
# Fond et texte de base
background #1D171E
# Un blanc legerement grise/rose pour être lisible mais doux
foreground #E2D9E0

# --- Couleurs de selection et curseur ---
selection_background #A32335
selection_foreground #1D171E
cursor #A32335
cursor_text_color #1D171E

# Les couleurs standards du terminal
# Noir
color0 #2E2525
color8 #382E36

# Rouge
color1 #A32335
color9 #C2293F

# Vert (desature pour coller au theme)
color2 #5B7A58
color10 #6B8F68

# Jaune (couleur or/cuivre)
color3 #A37C23
color11 #C29629

# Bleu (tire vers le violet/bordeaux)
color4 #4A3B4D
color12 #5A475D

# Magenta (rose fonce)
color5 #8A3B5D
color13 #A64770

# Cyan (gris/bleu canard)
color6 #4A7A7A
color14 #5A9494

# Blanc
color7 #E2D9E0
color15 #FFFFFF
